### ISSUE TITLE
v4.3.0 causes "main" entry error

### ISSUE THREAD

**Issue by rmunroe-utah** [rawify/Fraction.js#65]
Error received when running or building project:
Cannot find module '... /node_modules/fraction.js/fraction'. Please verify that the package.json has a valid "main" entry

**Comment by infusion** [comment]
should be fixed now, sorry. Just released the ES module integration and I forgot something. Thanks for the quick response on that!

**Comment by rmunroe-utah** [comment]
Thanks for the quick fix!
