### ISSUE TITLE
mathjs dependency error

### ISSUE THREAD

**Issue by cleversonmv** [rawify/Fraction.js#66]
on deploy today give that error in mathjs:

Uncaught TypeError: Object.defineProperty called on non-object
    at Function.defineProperty (<anonymous>)
    at push../node_modules/mathjs/lib/esm/type/fraction/Fraction.js.Object.isClass (Fraction.js:9:1)
    at assertAndCreate (factory.js:35:1)
    at ./node_modules/mathjs/lib/esm/entry/pureFunctionsAny.generated.js (pureFunctionsAny.generated.js:22:1)

**Comment by fc1904** [comment]
I encountered the same issue. It seems that both version 4.3.0 and 4.3.1 have this problem. I resolved it by manually changing the version number of `fraction.js` to 4.2.1 in the `yarn.lock` file, ensuring that my project doesn't throw errors for now.

**Comment by fc1904** [comment]
> 

I encountered the same issue. It seems that both version 4.3.0 and 4.3.1 have this problem. I resolved it by manually changing the version number of `fraction.js` to 4.2.1 in the `yarn.lock` file, ensuring that my project doesn't throw errors for now.

**Comment by infusion** [comment]
Please upgrade to 4.3.4, we discussed this here https://github.com/josdejong/mathjs/issues/3022
