### ISSUE TITLE
ERR_REQUIRE_ESM after latest update

### ISSUE THREAD

**Issue by RavimDhinesh** [rawify/Fraction.js#67]
Hi, 

From Today am getting the below error in fraction.js. Any solution please?

<img width="952" alt="Screenshot 2023-09-01 at 16 24 27" src="https://github.com/rawify/Fraction.js/assets/96374887/aecfc9cd-0904-41b2-b52e-1ecff984d650">

**Comment by infusion** [comment]
With the latest 4.3.5?

**Comment by RavimDhinesh** [comment]
Yes. It was updating from autoprefixer library. I installed 4.3.0 and the error was gone. please suggest as this blocks us

**Comment by infusion** [comment]
Sorry for the inconvenience, this stuff is getting a bit tricky. Could you please try again without the version fix, I just released a new version.

**Comment by RavimDhinesh** [comment]
It worked. thanks for the quick fix
