### ISSUE TITLE
Error importing fraction.js/bigint

### ISSUE THREAD

**Issue by pgte** [rawify/Fraction.js#69]
Hello,

I'm having the following error when compiling TS:

```
Module not found: Error: Package path ./bigfraction is not exported from package /home/runner/work/project/node_modules/fraction.js (see exports field in /home/runner/work/project/node_modules/fraction.js/package.json)
```

The import statement that's failing is this:

```js
import Fraction from 'fraction.js/bigfraction';
```

Is this no longer supported? If not, how can I import the big fraction version?

**Comment by infusion** [comment]
I think you have to enter the full path. Did it work with the statement you wrote previously? 

Just to let you know, there will soon be Fraction.js v5 which will be based on BigInt. The current change to make Fraction.js an ESM module was the first step to modernize the package.

**Comment by pgte** [comment]
> I think you have to enter the full path. Did it work with the statement you wrote previously?

Assuming the full path is `fraction.js/bigfraction`, no, the import statement I pasted here didn't work, and it failed with the following error:

```
Module not found: Error: Package path ./bigfraction is not exported from package /Users/pedroteixeira/projects/project/node_modules/fraction.js (see exports field in /Users/pedroteixeira/projects/project/node_modules/fraction.js/package.json)
```

**Comment by infusion** [comment]
bigfraction.js was just shipped experimentally, as I said it will become soon v5. If you want to use it now, you can import it with 

```js
import Fraction from './node_modules/fraction.js/bigfraction.js';
```

**Comment by pgte** [comment]
@infusion thanks, but I still get the same error.
I think we'll wait for version 5.
Thanks!

**Comment by infusion** [comment]
Until that you can just copy over the bigfraction.js file into your project.

**Comment by infusion** [comment]
V5 just released, which is natively is based on bigint.
