### ISSUE TITLE
simplify to arbitrary fraction

### ISSUE THREAD

**Issue by cranium** [rawify/Fraction.js#71]
Is there a way with the library to floor a given decimal input to a multiple of a fraction? I.e. `new Fraction("0.9").simplify(Fraction("1/8")) => Fraction("7/8")`. Would there be any interest in adding this?

I'm sort of confused what the use case for the existing `simplify` method is.

**Comment by infusion** [comment]
Interesting, you're the second to come up with this requirement. Back then it was #45, where I derived a function for it. The method I derived there can be used here as well:

```
let a = Fraction("0.9");
let b = Fraction("1/8");

Fraction(Math.round(a.n / a.d * b.d / b.n), b.d)
```

But I'll add this as a new function `roundTo()` which seems to described this behavior quite well. Or do you have another idea for this function?

**Comment by infusion** [comment]
Ah, sorry. I need my second factor password I have lying at home. I'll publish the new version later.

**Comment by infusion** [comment]
The use case for `simplify()` is you may have a fraction like `9999999999 / 10000000000 = 0.9999999999`, which is pretty close to 1. If you don't want big numbers in the numerator and denominator, you could say an error of 0.00001 is okay. This way the rational number is re-created with a simpler rational number which is pretty close to the original:

```js
Fraction("9999999999 / 10000000000").simplify(0.0001) // = 1
```

**Comment by cranium** [comment]
Got it- thanks for the context! Really appreciate the fast response. I was gonna offer to implement myself but you beat me to it.
