### ISSUE TITLE
TypeScript: TypeError: default is not a constructor errors

### ISSUE THREAD

**Issue by jayaddison** [rawify/Fraction.js#72]
This is an error I encounter on v4.3.5 but _not_ in v4.3.3 and earlier.

The TypeScript code I'm using is fairly similar to the [`README` example](https://github.com/rawify/Fraction.js#using-fractionjs-with-typescript).

```typescript
import * as assert from 'assert';
import { describe, it } from 'mocha';

import Fraction from 'fraction.js';


describe('repro case', function() {

  it('constructs fraction', function() {
    const result: string = new Fraction('1.23').simplify(0.1).toFraction(true);
    assert.equal('1.2', result);
  });

});
```

The error output when this test runs is:

```
  1) repro case
       constructs fraction:
     TypeError: fraction_js_1.default is not a constructor
      at Context.<anonymous> (src/app/repro.spec.ts:10:28)
      at processImmediate (node:internal/timers:471:21)
```

The contents of my local `tsconfig.json` file are: `{"include": ["src/**/*.ts"]}`

**Comment by frostburn** [comment]
This happened to me after updating `typescript` to `^4.9.5`.

**Comment by jayaddison** [comment]
Ok, hm.  This was found using TypeScript 5.2.2 and running a unit test using `mocha`.

Trying to remove `mocha` from the equation seems to help: the following code runs with no problems when run using `ts-node`:

```javascript
import Fraction from 'fraction.js';

const result: string = new Fraction('1.23').simplify(0.1).toFraction(true);
console.log(result);
```

Output:

```
$ ts-node foo.ts
1 1/4
```

(as expected)

That seems like it could  rule out `fraction.js` as the source of the problem, at least in the `mocha` test case.

**Comment by jayaddison** [comment]
Ah, blast.  That output was produced using `fraction.js` v4.2.1 - potentially unaffected, as per the issue description.  I'll check again with v4.3.5 in a few moments.

**Comment by jayaddison** [comment]
Ok, yep: `fraction.js` v4.3.5 is indeed borken with the previously-mentioned minimal code snippet.

```javascript
import Fraction from 'fraction.js';

const result: string = Fraction('1.23').simplify(0.1).toFraction(true);
console.log(result);
```

```
$ ts-node foo.ts
oo.ts:3:24 - error TS2348: Value of type 'typeof Fraction' is not callable. Did you mean to include 'new'?

3 const result: string = Fraction('1.23').simplify(0.1).toFraction(true);
```

I'll try reducing the TypeScript version next, following up on @frostburn's comment.

**Comment by jayaddison** [comment]
No luck as far back as TypeScript v4.3.5 here - the minimal snippet (without any of the `mocha` module references) still seems to fail with v4.3.5 of Fraction.js - version coincidence coincidental..

In the previous comment I'd omitted the `new` keyword; restoring that produces the same initially-reported error message:

```
const result: string = new Fraction('1.23').simplify(0.1).toFraction(true);
                       ^
TypeError: fraction_js_1.default is not a constructor
```

I'm being a bit spammy here, so I'll pause for a while.

**Comment by infusion** [comment]
Could you guys please verify if the errors still exist with the latest release?

**Comment by jayaddison** [comment]
```typescript
// foo.ts
import Fraction from 'fraction.js';

const result: string = new Fraction('1.23').simplify(0.1).toFraction(true);
console.log(result);
```

**Before (fraction.js 4.3.5)**
```sh
$ npx tsc foo.ts
$ node foo.js 
/home/jka/Documents/reciperadar/foo/foo.js:4
var result = new fraction_js_1.default('1.23').simplify(0.1).toFraction(true);
             ^

TypeError: fraction_js_1.default is not a constructor
    at Object.<anonymous> (/home/jka/Documents/reciperadar/foo/foo.js:4:14)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49

Node.js v20.17.0
```

**After (fraction.js 5.0.2)**
```sh
$ npx tsc foo.ts
$ node foo.js 
1 1/4
```

Much better.  Thank you, @infusion!
