### ISSUE TITLE
Compile Instructions

### ISSUE THREAD

**Issue by TonyRippy** [rawify/Fraction.js#75]
Hello, and thank you for all your work on this library!

As part of a PR I was working on, I was trying to figure out how to regenerate the `fraction.min.js` file. The project `README.md` file mentions that you use [google-closure-compiler](https://github.com/google/closure-compiler) with advanced optimizations, but I was unable to find the right combination of compiler flags to get this working. If it helps, here is what I tried: [TonyRippy/Fraction.js#e3779a2](https://github.com/TonyRippy/Fraction.js/commit/e3779a24ef33fc0ffe70557832b3c3111cb26698) 

Would it be possible to publish instructions that document what compiler flags and other settings you use to build the project?

**Comment by infusion** [comment]
Hi Tony,

with Fraction V5 released just now you can 

```
npm run build
```

**Comment by TonyRippy** [comment]
Awesome, thank you!
