### ISSUE TITLE
Plans with the bigfraction.js version?

### ISSUE THREAD

**Issue by josdejong** [rawify/Fraction.js#77]
I was trying out the `bigfraction.js` version, but encounter some small issues trying to import in an ES module, depending on how I try to import it, I get errors like:

```
Package subpath './bigfraction.js' is not defined by "exports"

The requested module '[...]/node_modules/fraction.js/bigfraction.js' does not provide an export named 'Fraction'

TypeError: Cannot set properties of undefined (setting 'Fraction')
at [...]/node_modules/fraction.js/bigfraction.js:896:22
at [...]/node_modules/fraction.js/bigfraction.js:899:3
```

The bigfraction.js version is [marked as experimental](https://github.com/rawify/Fraction.js?tab=readme-ov-file#precision), and it mentions version `v4.2.1 20/08/2023` whereas `fraction.js` is currently at `v4.3.7 31/08/2023`. Do you have plans to bring it on par again?

**Comment by infusion** [comment]
Fraction V5 is now based on bigint.
